# KFold Cross Validation

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np
import matplotlib.pyplot as plt

In [2]:
digits = load_digits()

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [16]:
def model_scores(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [17]:
logReg_score = model_scores(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train, X_test, y_train, y_test)
SVM_score = model_scores(SVC(gamma='auto'),X_train, X_test, y_train, y_test)
RandomForest_score = model_scores(RandomForestClassifier(n_estimators=40),X_train, X_test, y_train, y_test)

In [18]:
print(logReg_score, SVM_score, RandomForest_score) #everytime run split method, the train/test data will change, score will change

0.9462962962962963 0.49444444444444446 0.9629629629629629


### KFold Cross Validation

### divide the whole data into k groups, each time use one different group as test data

In [19]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3) # here split into 3 groups

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(model_scores(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(model_scores(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(model_scores(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [20]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [21]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [22]:
scores_rf

[0.9282136894824707, 0.9499165275459098, 0.9215358931552587]

### cross_val_score function

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [26]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [27]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92153589, 0.94824708, 0.91652755])

### Parameter tunning using k fold cross validation

#### use average score to determine the best parameters

In [28]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8797734326505277

In [29]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target, cv=10)
np.average(scores1)

0.9126412166356299

In [32]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores1)

0.943240223463687

In [33]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores1)

0.9443544382371197

In [34]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)
np.average(scores1)

0.9371073867163252